name: Build Plugins

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src
          
      # You'll need to add each plugin as an artifact here
      #Example:
      # - name: Upload
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: MyArtifactName
      #     path: src/MyPluginFolder/bin/x64/Release/net6.0/publish
