name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install templates
        run: dotnet new --install src/templates

      - name: Create Empty plugin
        run: dotnet new artemis-plugin-empty -n Artemis.Plugins.ExamplePlugin
      
      - name: Build new plugin
        run: dotnet build Artemis.Plugins.ExamplePlugin/Artemis.Plugins.ExamplePlugin.csproj -c Release
