name: Publish Template Nuget packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Pack
        run: dotnet pack -c Release src/Artemis.Templates.csproj

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: src/bin/Release/*.nupkg
